version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stock-prediction-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/saved_models:/app/saved_models
      - ./backend/uploads:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1
      - TF_CPP_MIN_LOG_LEVEL=2
    networks:
      - stock-prediction-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stock-prediction-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - stock-prediction-network
    restart: unless-stopped

networks:
  stock-prediction-network:
    driver: bridge

volumes:
  model-data:
  upload-data:
